server:
  port: ${tian-shan.server.port}

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${tian-shan.datasource.driver-class-name}
      url: jdbc:mysql://${tian-shan.datasource.host}:${tian-shan.datasource.port}/${tian-shan.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${tian-shan.datasource.username}
      password: ${tian-shan.datasource.password}

mybatis-plus:
  type-aliases-package: com.akbar.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# jwt配置信息
tian-shan:
  jwt:
    admin-secret-key: TIHGjrruCw2k6DAwcgbPRZvJvvwCwI4xYHZhgrErHs4=
    admin-ttl: 7200000  # 2小时(7200000ms)
    admin-token-name: token

  # 阿里云oss配置信息
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
    region: